name: Your New Jekyll Site

# Dependencies
markdown: redcarpet
pygments: true

#

baseurl: 		/designgov-2

# Permalinks
permalink:        /:title.html

# Server
destination:      ./_site
exclude:          [".editorconfig", "vendor", ".gitignore", "bower.json", "composer.json", "CNAME", "LICENSE", "node_modules", "README.md",]
port:             9001

# Custom vars
current_version:  3.0.3
repo:             https://github.com/twbs/bootstrap

download_source:  https://github.com/twbs/bootstrap/archive/v3.0.3.zip
download_dist:    https://github.com/twbs/bootstrap/releases/download/v3.0.3/bootstrap-3.0.3-dist.zip

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js

#vars

url: 			http://alanjosephwilliams.github.io
baseurl:		/designgov-2

# Plugins

lunr_search:
  excludes: [rss.xml, atom.xml]